SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Mst_ItemGroup](
	[IGrID] [int] IDENTITY(1,1) NOT NULL,
	[IGrName] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AcID] [numeric](18, 0) NULL
) ON [PRIMARY]

GO
